Taskmanager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('task_manager.urls')),
    path('admin/', admin.site.urls),
]

task_manager/urls.py
"""Task Manager URL Configuration

"""
from django.urls import path

from task_manager import views

app_name = 'task_manager'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('teams/<int:team_id>/', views.team_detail, name='team_detail'),
    path('teams/create/', views.team_create, name='team_create'),
    path('teams/<int:team_id>/remove-member/',
         views.team_remove_member, name='team_remove_member'),
    path('teams/<int:team_id>/add-member/',
         views.team_add_member, name='team_add_member'),
    path('teams/<int:team_id>/delete/', views.team_delete, name='team_delete'),
    path('my-tasks/', views.tasks, name='task_my_tasks'),
    path('my-completed-tasks/', views.completed_tasks,
         name='task_completed_tasks'),
    path('tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    path('tasks/<int:task_id>/edit/', views.task_edit, name='task_edit'),
    path('tasks/<int:task_id>/comment/',
         views.task_comment, name='task_comment'),
    path('tasks/<int:task_id>/accept/', views.task_accept, name='task_accept'),
    path('tasks/<int:task_id>/mark-completed/',
         views.task_mark_completed, name='task_mark_completed'),
    path('tasks/<int:task_id>/delete/', views.task_delete, name='task_delete'),
    path('tasks/create/', views.task_create, name='task_create'),
    path('tasks/search/', views.task_search, name='task_search'),
]

task_manager/models.py
import datetime

from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model

# Get user model defined in settings.AUTH_USER_MODEL
# Better to call get_user_model in pluggable app instead of imporing User from django.contrib.auth.models
UserModel = get_user_model()


class Team(models.Model):
    """
    Not using Django's built-in Group model because we want
    to save the creater of team.
    """
    name = models.CharField(max_length=50)
    desc = models.TextField(default='', max_length=1024, blank=True)
    leader = models.ForeignKey(
        UserModel, on_delete=models.CASCADE, related_name='leading_teams')
    members = models.ManyToManyField(UserModel)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("task_manager:team_detail", kwargs={"team_id": self.id})

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Teams"


class Task(models.Model):
    title = models.CharField(max_length=50)
    desc = models.TextField(default="", max_length=1024, blank=True)
    STATUS_CHOICES = (
        ('PLAN', 'Planned'),
        ('PROG', 'In Progress'),
        ('COMP', 'Completed')
    )
    status = models.CharField(
        max_length=4, choices=STATUS_CHOICES, default='PLAN')

    creator = models.ForeignKey(
        UserModel, on_delete=models.CASCADE, related_name='created_tasks')

    # A task can be assigned to one or many users
    assigned_to = models.ManyToManyField(
        UserModel, help_text="Press ctrl to select multiple")

    team = models.ForeignKey(
        Team, on_delete=models.SET_NULL, null=True, blank=True)

    planned_date = models.DateField(auto_now_add=True)
    accepted_date = models.DateField(null=True, blank=True)
    accepted_by = models.ForeignKey(
        UserModel, on_delete=models.SET_NULL, null=True, related_name='accepted_tasks', blank=True)
    due_date = models.DateField()
    completed_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("task_manager:task_detail", kwargs={"task_id": self.id})

    # Has due date for an instance of this object passed?
    def is_overdated(self):
        """Returns whether the Tasks's due date has passed or not."""
        if self.due_date and datetime.date.today() > self.due_date:
            return True
        else:
            return False

    class Meta:
        ordering = ["planned_date"]
        verbose_name_plural = "Tasks"


class Comment(models.Model):
    author = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    comment_datetime = models.DateTimeField(auto_now_add=True)
    body = models.TextField()

    def snippet(self):
        """
        Returns a short version of comment body with auther's username as prefix
        """
        return "{author} - {snippet}...".format(author=self.author, snippet=self.body[:36])

    def __str__(self):
        return self.snippet()

    class Meta:
        ordering = ["-comment_datetime"]

task_manager/views/index.py
from django.shortcuts import render
from django.views.decorators.http import require_http_methods

from task_manager.models import Team


@require_http_methods(["GET"])
def index(request):
    if request.user.is_authenticated:
        teams = request.user.team_set.all()
        return render(
            request,
            'task_manager/index.html',
            {'user': request.user, 'teams': teams}
        )
    else:
        return render(request, 'task_manager/index.html', {'user': request.user})

task_manager/views/search.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.views.decorators.http import require_http_methods

from task_manager.models import Task


@login_required
@require_http_methods(["GET"])
def task_search(request):
    """
    Search for tasks user has permission to see.
    """
    query_string = ""
    found_tasks = None
    if ("q" in request.GET) and request.GET["q"].strip():
        query_string = request.GET["q"]

        found_tasks = Task.objects.filter(
            (Q(title__icontains=query_string) | Q(desc__icontains=query_string)) &
            (Q(creator=request.user) | Q(assigned_to=request.user))
        ).distinct()
    else:
        messages.error(request, "Missing search parameter!")

    context = {"query_string": query_string, "found_tasks": found_tasks}
    return render(request, "task_manager/task_search_results.html", context)

task_manager/views/tasks.py
import datetime

from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods

from task_manager.models import Team, Task, Comment
from task_manager.forms import TaskCreationForm, TaskEditForm


@login_required
@require_http_methods(["GET", "POST"])
def task_create(request):
    """
    Any authenticated user is able to create task.
    """
    # Get request.user's teams
    teams = Team.objects.filter(leader=request.user)
    if request.method == 'POST':
        form = TaskCreationForm(request.POST, initial={'teams': teams})
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.creator = request.user
            new_task.save()
            # Task is firstly assigned to creator
            new_task.assigned_to.add(request.user)
            messages.success(
                request, "Task: `{0}` is created successfully!".format(new_task.title))
            # Task is created succesfully, redirect user to new task's detail page
            return redirect(new_task)
        else:
            # Form is not valid, send back with errors
            return render(
                request,
                'task_manager/task_create-edit.html',
                {'user': request.user, 'form': form, 'creation': True}
            )
    else:
        form = TaskCreationForm(initial={'teams': teams})
        return render(
            request,
            'task_manager/task_create-edit.html',
            {'user': request.user, 'form': form, 'teams': teams, 'creation': True}
        )


@login_required
@require_http_methods(["GET", "POST"])
def task_edit(request, task_id):
    """
    Only task creator is able to edit task.
    """
    task = get_object_or_404(Task, id=task_id)
    # Only task creator is allowed to edit task whose status is 'Planned'
    if request.user == task.creator and task.status == 'PLAN':
        teams = Team.objects.filter(leader=request.user)
        has_team = True if task.team else False
        members = task.team.members.all() if has_team else None
        if request.method == 'POST':
            form = TaskEditForm(
                request.POST,
                instance=task,
                initial={'members': members,
                         'has_team': has_team, 'teams': teams}
            )
            if form.is_valid():
                form.save()
                messages.success(
                    request, "The changes are saved successfully!")
                return redirect(task)
            else:
                # Form is not valid, send back with errors
                return render(
                    request,
                    'task_manager/task_create-edit.html',
                    {'user': request.user, 'form': form,
                        'task': task, 'creation': False}
                )
        else:
            form = TaskEditForm(
                instance=task,
                initial={'members': members,
                         'has_team': has_team, 'teams': teams}
            )
            return render(
                request,
                'task_manager/task_create-edit.html',
                {'user': request.user, 'form': form,
                    'task': task, 'creation': False}
            )
    else:
        raise PermissionDenied


@login_required
@require_http_methods(["GET"])
def task_delete(request, task_id):
    """
    Only task creator can delete task if task is IN-PROGRESS.
    """
    task = get_object_or_404(Task, id=task_id)
    if request.user == task.creator and task.status == 'PLAN':
        task.delete()
        messages.success(request, "The task is deleted successfully!")
        # After deleting task redirect user to index page with success message
        return redirect('task_manager:index')
    else:
        # User is not creator of task, raise PermissionDenied
        raise PermissionDenied


@login_required
@require_http_methods(["GET"])
def tasks(request):
    """
    Any authenticated user is able to see incomplete tasks
    created or assigned to him.
    """
    tasks = Task.objects.filter(
        Q(creator=request.user) | Q(assigned_to=request.user)
    ).exclude(status="COMP").distinct()
    return render(
        request,
        'task_manager/tasks.html',
        {'user': request.user, 'tasks': tasks, 'completed': False}
    )


@login_required
@require_http_methods(["GET"])
def completed_tasks(request):
    """
    Any authenticated user is able to see completed tasks
    created or assigned to him.
    """
    tasks = Task.objects.filter(
        Q(creator=request.user) | Q(assigned_to=request.user)
    ).filter(status="COMP").distinct()
    return render(
        request,
        'task_manager/tasks.html',
        {'user': request.user, 'tasks': tasks, 'completed': True}
    )


@login_required
@require_http_methods(["GET"])
def task_detail(request, task_id):
    """
    Only task creator and members of task's team can see details of task.
    """
    task = get_object_or_404(Task, id=task_id)
    if request.user == task.creator or request.user in task.assigned_to.all():
        allowed = True
    elif task.team:
        if request.user in task.team.members.all():
            allowed = True
        else:
            allowed = False
    else:
        allowed = False
    # If user is allowed to see details return details else raise PermissionDenied
    if allowed:
        return render(
            request,
            'task_manager/task_detail.html',
            {'user': request.user, 'task': task}
        )
    else:
        raise PermissionDenied


@login_required
@require_http_methods(["GET"])
def task_accept(request, task_id):
    """
    Only assigned users can accept task and mark as In-Progress.
    """
    task = get_object_or_404(Task, id=task_id)
    if request.user in task.assigned_to.all():
        if task.status == 'PLAN':
            task.status = 'PROG'
            task.task_accepted_on = datetime.date.today()
            task.task_accepted_by = request.user
            task.save()
            messages.success(
                request, "The task has marked as In-Progress successfully!")
            # After marking task as In-Progress, redirect user to that task with success message
            return redirect(task)
        else:
            raise PermissionDenied
    else:
        raise PermissionDenied


@login_required
@require_http_methods(["GET"])
def task_mark_completed(request, task_id):
    """
    Only task creator and assigned users can mark task as Completed.
    """
    task = get_object_or_404(Task, id=task_id)
    if request.user == task.creator or request.user in task.assigned_to.all():
        if task.status == 'PROG':
            task.status = 'COMP'
            task.completed_date = datetime.date.today()
            task.save()
            messages.success(
                request, "The task is marked as Completed successfully!")
            # After marking task as completed, redirect user to that task with success message
            return redirect(task)
        else:
            raise PermissionDenied
    else:
        raise PermissionDenied


@login_required
@require_http_methods(["POST"])
def task_comment(request, task_id):
    """
    Only task creator, assigned users and members of task's team can comment on task.
    """
    task = get_object_or_404(Task, id=task_id)
    if request.user == task.creator or request.user in task.assigned_to.all():
        allowed = True
    elif task.team:
        if request.user in task.team.members.all():
            allowed = True
        else:
            allowed = False
    else:
        allowed = False
    # If user is allowed to comment, add comment else raise PermissionDenied
    if allowed:
        if request.POST.get('comment_body').strip():
            comment = Comment(
                author=request.user,
                task=task,
                body=request.POST['comment_body']
            )
            comment.save()
            messages.success(request, "The comment is added succesfully")
            # After adding the comment, redirect user to that task with success message
            return redirect(task)
        else:
            messages.error(request, "Missing required fields")
            return redirect(task)
    else:
        raise PermissionDenied

task_manager/templates/task_manager/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head lang="en">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'task_manager/w3.css' %}">
  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  <!-- Sidebar -->
  <div class="w3-sidebar w3-bar-block w3-border-right w3-animate-left" style="display:none" id="mySidebar">
    <button onclick="w3_close()" class="w3-bar-item w3-large">Close &times;</button>
    {% if user.is_authenticated %}
    <strong class="w3-bar-item"><i>{{ user.username }}</i></strong>
    <a href="{% url 'task_manager:index' %}" class="w3-bar-item w3-button">My Teams</a>
    <a href="{% url 'task_manager:task_my_tasks' %}" class="w3-bar-item w3-button">My Tasks</a>
    <a href="{% url 'task_manager:task_completed_tasks' %}" class="w3-bar-item w3-button">Completed Tasks</a>
    <a href="{% url 'task_manager:task_create' %}" class="w3-bar-item w3-button">Plan a Task</a>
    <a href="{% url 'task_manager:team_create' %}" class="w3-bar-item w3-button">Create a Team</a>
    <form method="get" action="{% url 'task_manager:task_search' %}" class="w3-margin-top w3-margin-bottom">
      <input type="text" name="q" class="w3-input w3-border" placeholder="Search task" required>
      <input type="submit" value="Search" class="w3-button w3-grey w3-margin">
    </form>
    <a href="{% url 'task_manager:logout' %}" class="w3-bar-item w3-button">LogOut</a>
    {% else %}
    <a href="{% url 'task_manager:signup' %}" class="w3-bar-item w3-button">Sign Up</a>
    <a href="{% url 'task_manager:login' %}" class="w3-bar-item w3-button">Log In</a>
    {% endif %}
  </div>

  <!-- Page Content -->
  <div class="w3-teal">
    <button class="w3-button w3-teal w3-xlarge" onclick="w3_open()">☰</button>
    <div class="w3-container">
      <h1 style="text-shadow:1px 1px 0 #444">Task Manager</h1>
    </div>
  </div>

  <div class="w3-container">
    {% if messages %}
    {% for message in messages %}
    <div
      class="w3-panel w3-round-xlarge {% if message.tags == 'success' %}w3-pale-green{% else %}w3-pale-red{% endif %}"
      style="padding:10px">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% block content %}{% endblock %}
  </div>

  <script>
    function w3_open() {
      document.getElementById("mySidebar").style.display = "block";
    }
    function w3_close() {
      document.getElementById("mySidebar").style.display = "none";
    }
  </script>
</body>

</html>

task_manager/templates/task_manager/index.html
{% extends "./base.html" %}

{% block content %}
<div class="jumbotron">
    <h1 class="display-4">Task Manager</h1>
    <p class="lead">A multi-user, multi-team task management and assignment system.</p>
    <hr class="my-4">

</div>
{% endblock %}

task_manager/templates/task_manager/login.html
{% extends "./base.html" %} {% block content %}

<div class="container mt-5">
  <form method="post" action="">
    {% csrf_token %}
    <div class="form-group">
      <label for="username">Username</label>
      <input
        type="text"
        class="form-control"
        id="username"
        aria-describedby="emailHelp"
        placeholder="Enter username"
      />
      <small id="emailHelp" class="form-text text-muted"
        >We'll never share your email with anyone else.</small
      >
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input
        type="password"
        class="form-control"
        id="password"
        placeholder="Password"
      />
      <input type="hidden" name="next" value="{{ next }}" />
    </div>
    <button type="submit" value="login" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock %}

task_manager/templates/task_manager/task_create-edit.html
{% extends './base.html' %}

{% block title %}
  {% if creation %}
    Create task | Task Manager
  {% else %}
    Edit task | Task Manager
  {% endif %}
{% endblock %}

{% block content %}

  <div class="w3-container w3-card w3-margin-top">
    <form method="post" action="">
      {% csrf_token %}

        {% for field in form %}
          <div class="w3-margin">

            {% for error in field.errors %}
              <div class="w3-panel w3-pale-red w3-round-xlarge">
                {{ error }}
              </div>
            {% endfor %}

            <b>{{ field.label_tag }}</b>
            {{ field }}
            {% if field.help_text %}
              <span class="w3-small">
                {{ field.help_text }}
              </span>
            {% endif %}
          </div>
        {% endfor %}

      <input type="submit" value="{% if creation %}Create Task{% else %}Save Changes{% endif %}" class="w3-button w3-green w3-margin w3-wide w3-right">

    </form>
    {% if not creation %}
      <a href="{% url 'task_manager:task_delete' task.id %}"><button class="w3-button w3-red w3-margin w3-left">Delete Task</button></a>
    {% endif %}
  </div>
{% endblock %}

task_manager/templates/task_manager/task_detail.html
{% extends './base.html' %}

{% block title %}
  Task: {{ task.title }} | Tasks Manager
{% endblock %}

{% block content %}
  <div class="w3-cell-row">
    <div class="w3-card w3-container w3-cell w3-cell-middle w3-mobile">
      <h2 class="w3-padding-16">{{ task.title }}</h2>

      {% if task.desc %}
        {{ task.desc|safe|urlize|linebreaks }}
      {% endif %}

      {# user having task assigned to and task creator can mark task as In-rogress or Completed #}
      {% if user in task.assigned_to.all or user == task.creator %}
        <div class="w3-bar w3-center">
          {% if task.status == 'PLAN' and user in task.assigned_to.all %}
            <a href="{% url 'task_manager:task_accept' task.id %}">
              <button class="w3-button w3-blue">Accept the Task</button>
            </a>
          {% endif %}
          {% if task.status == 'PROG' %}
            <a href="{% url 'task_manager:task_mark_completed' task.id %}">
              <button class="w3-button w3-blue w3-margin-bottom">Mark Completed</button>
            </a>
          {% endif %}

          {# Only task creator can edit the task #}
          {% if user == task.creator and task.status == 'PLAN' %}
            <a href="{% url 'task_manager:task_edit' task.id %}">
              <button class="w3-button w3-green w3-margin-bottom w3-margin-top">Edit Task</button>
            </a>
          {% endif %}
        </div>
      {% endif %}
    </div>

  <div class="w3-card w3-container w3-cell w3-cell-middle w3-mobile">
    <p class="w3-border-bottom"><strong>Created By : </strong><i>{{ task.creator }}</i></p>
      <p class="w3-border-bottom">
        <strong>Status : </strong>
        <span class="w3-tag w3-blue w3-round-large">{{ task.get_status_display }}</span>
      </p>
      <p><strong>Assigned To : </strong>
        <ul class="w3-ul w3-center">
        {% for u in task.assigned_to.all %}
          <li><i>{{ u }}</i></li>
        {% endfor %}
        </ul>
      </p>
      {% if task.team %}
        <p class="w3-border-bottom"><strong>Assigned to team : </strong>
          <a href="{{ task.team.get_absolute_url }}">{{ task.team }}</a>
        </p>
      {% endif %}
      <p class="w3-border-bottom"><strong>Planned on : </strong>{{ task.planned_date }}</p>
      <p class="w3-border-bottom"><strong>Due Date : </strong>{{ task.due_date }}</p>
      {% if task.status == 'PROG' or task.status == 'COMP' %}
        <p class="w3-border-bottom"><strong>Accepted on : </strong>{{ task.accepted_date }}</p>
        <p class="w3-border-bottom"><strong>Accepted By : </strong>{{ task.accepted_by }}</p>
      {% endif %}
      {% if task.status == 'COMP' %}
        <p class="w3-border-bottom"><strong>Completed on : </strong>{{ task.completed_date }}</p>
      {% endif %}
    </div>
  </div>

  <!-- Comment form -->
  <div class="w3-container">
    <h5>Add comment:</h5>
    <form action="{% url 'task_manager:task_comment' task.id %}" method="post">
      {% csrf_token %}
      <textarea class="w3-input w3-border" name="comment_body" rows="3" placeholder="Write your comment here" required></textarea>
      <input class="w3-button w3-wide w3-green w3-margin-top" type="submit" value="Add Comment">
    </form>
  </div>

  <!-- Comment's section -->
  <div class="w3-card w3-margin-top w3-container">
    <h4><b>Comments on this task:</b></h4>
    <hr>
    {% for comment in task.comment_set.all %}
      <p>
        <b>
          <i>{{ comment.author }}</i>,
          {{ comment.time }}
        </b>
      </p>
      {{ comment.body|safe|urlize|linebreaks }}
      <hr>
    {% empty %}
    No Comments (yet).
    <hr>
    {% endfor %}
  </div>

{% endblock %}

task_manager/templates/task_manager/task_search_results.html
{% extends './base.html' %}

{% block title %}
  Search results | Task Manager
{% endblock %}

{% block content %}
  <h2>{{ found_tasks.count }} search results for : "{{ query_string }}"</h2>
  {% if found_tasks %}
    <table class="w3-table w3-striped w3-bordered w3-card-4 w3-hoverable">
      <tr class="w3-green">
        <th>Title</th>
        <th>Team</th>
        <th>Created By</th>
        <th>Assigned to</th>
        <th>Due Date</th>
        <th>Status</th>
        <th>Completed Date</th>
      </tr>
      {% for task in found_tasks %}
        <tr>
          <td><a href="{{ task.get_absolute_url }}">{{ task.title }}</a></td>
          <td>
            {% if task.team %}
              <a href={{ task.team.get_absolute_url }}>{{ task.team }}</a>
            {% else %}
              ----
            {% endif %}
          </td>
          <td>{{ task.creator }}</td>
          <td>
            <ul class="w3-ul" style="width:36%">
              {% for u in task.assigned_to.all %}
                <li><i>{{ u }}</i></li>
              {% endfor %}
            </ul>
          </td>
          <td>{{ task.due_date }}</td>
          <td>{{ task.get_status_display }}</td>
          <td>{{ task.completed_date }}</td>
        </tr>
      {% endfor %}
    </table>
  {% endif %}

{% endblock %}

task_manager/templates/task_manager/tasks.html
{% extends "./base.html" %}

{% block title %}
  {% if completed %}
  Completed Tasks | Task Manager
  {% else %}
  My Tasks | Task Manager
  {% endif %}
{% endblock %}

{% block content %}
  <h2 class="w3-card w3-padding-16">
    {% if completed %}
      Completed Tasks:
    {% else %}
      My Tasks:
    {% endif %}
  </h2>
  <p>{{ tasks.count }} task(s) are found!</p>
  {% if tasks %}
    <table class="w3-table w3-striped w3-bordered w3-card-4 w3-hoverable">
      <tr class="w3-green">
        <th>Title</th>
        <th>Team</th>
        <th>Created By</th>
        <th>Assigned to</th>
        {% if not completed %}
          <th>Due Date</th>
          <th>Status</th>
        {% else %}
          <th>Completed Date</th>
        {% endif %}
      </tr>
      {% for task in tasks %}
        <tr>
          <td><a href="{{ task.get_absolute_url }}">{{ task.title }}</a></td>
          <td>
            {% if task.team %}
              <a href={{ task.team.get_absolute_url }}>{{ task.team }}</a>
            {% else %}
              ----
            {% endif %}
          </td>
          <td>{{ task.creator }}</td>
          <td>
            <ul class="w3-ul" style="width:36%">
              {% for u in task.assigned_to.all %}
                <li><i>{{ u }}</i></li>
              {% endfor %}
            </ul>
          </td>
          {% if not completed %}
            <td class="{% if task.is_overdated %}w3-red{% endif %}">{{ task.due_date }}</td>
            <td>{{ task.get_status_display }}</td>
          {% else %}
            <td>{{ task.completed_date }}</td>
          {% endif %}
        </tr>
      {% endfor %}
    </table>
  {% endif %}

{% endblock %}

task_manager/templates/task_manager/team_create.html
{% extends './base.html' %}

{% block title %}
  Create a Team | Task Manager
{% endblock %}

{% block content %}
  <div class="w3-card w3-margin-top">
    <form action="" method="post" class="w3-container">
      {% csrf_token %}
      <label>Team Name:</label>
      <input type="text" name="team_name" class="w3-input w3-margin-top w3-margin-bottom" placeholder="Enter name for team" required autofocus>
      <label>Team Description : </label>
      <textarea name="team_desc" rows="5" class="w3-input w3-border w3-margin-top" placeholder="Enter description of team"></textarea>
      <input type="submit" class="w3-button w3-green w3-margin w3-wide" value="Create Team">
    </form>
  </div>
{% endblock %}

task_manager/templates/task_manager/team_detail.html
{% extends "./base.html" %}

{% block title %}
  {{ team.name }} | Task Manager
{% endblock %}

{% block content %}
<div class="w3-card-4 w3-padding-16 w3-light-grey w3-margin-bottom w3-margin-top">
  <div class="w3-margin-left">
    <h2 class="">{{ team.name }}</h2>
    {% if team.desc %}
      <p>{{ team.desc|safe|linebreaks }}</p>
    {% endif %}
  </div>
  {% if team.members.count == 1 %}
    <div class="w3-margin">
      Your team is empty.
      <a href="{% url 'task_manager:team_delete' team.id %}">
        <button class="w3-button w3-red w3-margin">Delete Team</button>
      </a>
    </div>
  {% endif %}
</div>

<b>
  Tasks assigned to team :
</b>
<p>{{ tasks.count }} task(s) are assigned to team!</p>
{% if tasks %}
  <table class="w3-table w3-striped w3-bordered w3-card-4 w3-hoverable">
    <tr class="w3-green">
      <th>Title</th>
      <th>Assigned to</th>
      <th>Due Date</th>
      <th>Status</th>
    </tr>
    {% for task in tasks %}
      <tr>
        <td><a href="{{ task.get_absolute_url }}">{{ task.title }}</a></td>
        <td>
          <ul class="w3-ul" style="width:36%">
            {% for u in task.assigned_to.all %}
              <li><i>{{ u }}</i></li>
            {% endfor %}
          </ul>
        </td>
        <td class="{% if task.is_overdated %}w3-red{% endif %}">{{ task.due_date }}</td>
        <td>{{ task.get_status_display }}</td>
      </tr>
    {% endfor %}
  </table>
{% endif %}

<div class="w3-margin-top">
  <b><p>Members: </p></b>
  <ul class="w3-ul w3-card-2">
    {% for member in team.members.all %}
      <li class="w3-bar">
        <div class="w3-bar-item">
          <span class="w3-large">{{ member }}</span>
          {% if member == team.leader %}
            <span class="w3-badge w3-green">leader</span>
          {% endif %}
        </div>
        {% if user == team.leader and member != team.leader %}
          <a href="{% url 'task_manager:team_remove_member' team.id %}?username={{ member.username }}">
            <span class="w3-bar-item w3-button w3-large w3-right" style="color:red">Remove</span>
          </a>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
</div>

{# Members addition form #}
{% if user == team.leader %}
  <div class="w3-card w3-center w3-margin-top w3-row-padding">
  <form method="get" action="{% url 'task_manager:team_add_member' team.id %}" class="w3-container">
    <p class="w3-margin-top">Add a user with username:</p>
    <input class="w3-input w3-section" type="text" name="username" placeholder="Enter username of member to add" autocomplete="off" spellcheck="false" required>
    <input type="submit" value="Add user" class="w3-button w3-wide w3-green w3-section">
  </form>
  </div>
{% endif %}

{% endblock %}